package com.joedayz.corespringtest.domain;


/**
 * Tema generated by @author Susan Inga (susan.inga@joedayz.pe)
 */
public class Tema implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3180044230875881409L;
	private Long id;
	private String descripcion;

	public Tema() {
	}

	public Tema(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public String toString() {
		return "Tema [id=" + id + ", descripcion=" + descripcion + "]";
	}

	
}
