DROP TABLE IF EXISTS comentario;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS tema;

CREATE TABLE tema (
  ID int(20) NOT NULL AUTO_INCREMENT,
  DESCRIPCION varchar(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE post (
  ID int(20) NOT NULL AUTO_INCREMENT,
  TITULO varchar(50) NOT NULL,
  DESCRIPCION text NOT NULL,
  ID_TEMA int(20) NOT NULL,
  FECHA_CREACION datetime NOT NULL,
  PRIMARY KEY (ID),
 FOREIGN KEY  (ID_TEMA) REFERENCES tema (ID)
) ;

CREATE TABLE comentario (
  ID int(20) NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(50) NOT NULL,
  CORREO_ELECTRONICO varchar(50) NOT NULL,
  COMENTARIO text NOT NULL,
  ID_POST int(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_POST) REFERENCES post (ID)
);

