insert into T_ACCOUNT (NUMBER, NAME, CREDIT_CARD) values ('123456789', 'Keith and Keri Donald', '1234123412341234');
insert into T_ACCOUNT_BENEFICIARY (ACCOUNT_ID, NAME, ALLOCATION_PERCENTAGE, SAVINGS) values (0, 'Annabelle', .5, 0.00);
insert into T_ACCOUNT_BENEFICIARY (ACCOUNT_ID, NAME, ALLOCATION_PERCENTAGE, SAVINGS) values (0, 'Corgan', .5, 0.00);

insert into T_RESTAURANT (MERCHANT_NUMBER, NAME, BENEFIT_PERCENTAGE, BENEFIT_AVAILABILITY_POLICY) values ('1234567890', 'AppleBees', .08, 'A');