drop table T_ACCOUNT_BENEFICIARY if exists;
drop table T_ACCOUNT_CREDIT_CARD if exists;
drop table T_ACCOUNT if exists;
drop table T_RESTAURANT if exists;
drop table T_REWARD if exists;
drop sequence S_REWARD_CONFIRMATION_NUMBER if exists;
drop table DUAL_REWARD_CONFIRMATION_NUMBER if exists;

create table T_ACCOUNT( id bigint generated by default as identity (start with 1), 
						number varchar(9),
						name varchar(50) not null, 
						unique(number),
						primary key (id));

create table T_ACCOUNT_CREDIT_CARD( id bigint generated by default as identity (start with 1), 
						account_id bigint,
						number varchar(16), 
						unique(account_id, number),
						foreign key (account_id) references T_ACCOUNT(id));		
						
create table T_ACCOUNT_BENEFICIARY( id bigint generated by default as identity (start with 1), 
						account_id bigint,
						name varchar(50), 
						allocation_percentage double not null,
						savings double not null,
						unique(account_id, name),
						foreign key (account_id) references T_ACCOUNT(id));								
						
create table T_RESTAURANT( id bigint generated by default as identity (start with 1), 
						merchant_number varchar(10) not null,
						name varchar(80), 
						benefit_percentage double not null,
						benefit_availability_policy varchar(1) not null,
						unique(MERCHANT_NUMBER));		

create table T_REWARD( id bigint generated by default as identity (start with 1), 
						confirmation_number varchar(25) not null,						
						reward_amount double not null,
						reward_date date not null,
						account_number varchar(9) not null,
						dining_amount double not null, 
						dining_merchant_number varchar(10) not null, 
						dining_date date not null, 						
						unique(CONFIRMATION_NUMBER));	


create sequence S_REWARD_CONFIRMATION_NUMBER start with 1;
create table DUAL_REWARD_CONFIRMATION_NUMBER (ZERO bigint);
insert into DUAL_REWARD_CONFIRMATION_NUMBER values (0);
